# Generated by Django 2.2 on 2021-02-21 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cmc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='mtg_app.Cmc'),
        ),
        migrations.AddField(
            model_name='card',
            name='power',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='mtg_app.Power'),
        ),
        migrations.AddField(
            model_name='card',
            name='toughness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='mtg_app.Toughness'),
        ),
    ]
