from mtg_app.models import *

new_Artifact = Artifact.objects.create(card_type="Artifact")
new_Conspiracy = Conspiracy.objects.create(card_type="Conspiracy")
new_Creature = Creature.objects.create(card_type="Creature")
new_Enchantment = Enchantment.objects.create(card_type="Enchantment")
new_Instant = Instant.objects.create(card_type="Instant")
new_Land = Land.objects.create(card_type="Land")
new_Phenomenon = Phenomenon.objects.create(card_type="Phenomenon")
new_Plane = Plane.objects.create(card_type="Plane")
new_Planeswalker = Planeswalker.objects.create(card_type="Planeswalker")
new_Scheme = Scheme.objects.create(card_type="Scheme")
new_Sorcery = Sorcery.objects.create(card_type="Sorcery")
new_Tribal = Tribal.objects.create(card_type="Tribal")
new_Vanguard = Vanguard.objects.create(card_type="Vanguard")
new_Adamant = Adamant.objects.create(keyword="Adamant")
new_Adapt = Adapt.objects.create(keyword="Adapt")
new_Addendum = Addendum.objects.create(keyword="Addendum")
new_Affinity = Affinity.objects.create(keyword="Affinity")
new_Afflict = Afflict.objects.create(keyword="Afflict")
new_Afterlife = Afterlife.objects.create(keyword="Afterlife")
new_Aftermath = Aftermath.objects.create(keyword="Aftermath")
new_Amass = Amass.objects.create(keyword="Amass")
new_Amplify = Amplify.objects.create(keyword="Amplify")
new_Annihilator = Annihilator.objects.create(keyword="Annihilator")
new_Ascend = Ascend.objects.create(keyword="Ascend")
new_Assemble = Assemble.objects.create(keyword="Assemble")
new_Assist = Assist.objects.create(keyword="Assist")
new_Augment = Augment.objects.create(keyword="Augment")
new_Aura_Swap = Aura_Swap.objects.create(keyword="Aura Swap")
new_Awaken = Awaken.objects.create(keyword="Awaken")
new_Banding = Banding.objects.create(keyword="Banding")
new_Basic_landcycling = Basic_landcycling.objects.create(keyword="Basic landcycling")
new_Battalion = Battalion.objects.create(keyword="Battalion")
new_Battle_Cry = Battle_Cry.objects.create(keyword="Battle Cry")
new_Bestow = Bestow.objects.create(keyword="Bestow")
new_Bloodrush = Bloodrush.objects.create(keyword="Bloodrush")
new_Bloodthirst = Bloodthirst.objects.create(keyword="Bloodthirst")
new_Boast = Boast.objects.create(keyword="Boast")
new_Bolster = Bolster.objects.create(keyword="Bolster")
new_Bushido = Bushido.objects.create(keyword="Bushido")
new_Buyback = Buyback.objects.create(keyword="Buyback")
new_Cascade = Cascade.objects.create(keyword="Cascade")
new_Champion = Champion.objects.create(keyword="Champion")
new_Changeling = Changeling.objects.create(keyword="Changeling")
new_Channel = Channel.objects.create(keyword="Channel")
new_Chroma = Chroma.objects.create(keyword="Chroma")
new_Cipher = Cipher.objects.create(keyword="Cipher")
new_Clash = Clash.objects.create(keyword="Clash")
new_Cohort = Cohort.objects.create(keyword="Cohort")
new_Commander_ninjutsu = Commander_ninjutsu.objects.create(keyword="Commander ninjutsu")
new_Companion = Companion.objects.create(keyword="Companion")
new_Conspire = Conspire.objects.create(keyword="Conspire")
new_Constellation = Constellation.objects.create(keyword="Constellation")
new_Converge = Converge.objects.create(keyword="Converge")
new_Convoke = Convoke.objects.create(keyword="Convoke")
new_Councils_dilemma = Councils_dilemma.objects.create(keyword="Councils dilemma")
new_Crew = Crew.objects.create(keyword="Crew")
new_Cumulative_upkeep = Cumulative_upkeep.objects.create(keyword="Cumulative upkeep")
new_Cycling = Cycling.objects.create(keyword="Cycling")
new_Dash = Dash.objects.create(keyword="Dash")
new_Deathtouch = Deathtouch.objects.create(keyword="Deathtouch")
new_Defender = Defender.objects.create(keyword="Defender")
new_Delirium = Delirium.objects.create(keyword="Delirium")
new_Delve = Delve.objects.create(keyword="Delve")
new_Desertwalk = Desertwalk.objects.create(keyword="Desertwalk")
new_Detain = Detain.objects.create(keyword="Detain")
new_Dethrone = Dethrone.objects.create(keyword="Dethrone")
new_Devoid = Devoid.objects.create(keyword="Devoid")
new_Devour = Devour.objects.create(keyword="Devour")
new_Domain = Domain.objects.create(keyword="Domain")
new_Double_strike = Double_strike.objects.create(keyword="Double strike")
new_Dredge = Dredge.objects.create(keyword="Dredge")
new_Echo = Echo.objects.create(keyword="Echo")
new_Embalm = Embalm.objects.create(keyword="Embalm")
new_Emerge = Emerge.objects.create(keyword="Emerge")
new_Eminence = Eminence.objects.create(keyword="Eminence")
new_Enchant = Enchant.objects.create(keyword="Enchant")
new_Enrage = Enrage.objects.create(keyword="Enrage")
new_Entwine = Entwine.objects.create(keyword="Entwine")
new_Epic = Epic.objects.create(keyword="Epic")
new_Equip = Equip.objects.create(keyword="Equip")
new_Escalate = Escalate.objects.create(keyword="Escalate")
new_Escape = Escape.objects.create(keyword="Escape")
new_Eternalize = Eternalize.objects.create(keyword="Eternalize")
new_Evoke = Evoke.objects.create(keyword="Evoke")
new_Evolve = Evolve.objects.create(keyword="Evolve")
new_Exalted = Exalted.objects.create(keyword="Exalted")
new_Exert = Exert.objects.create(keyword="Exert")
new_Exploit = Exploit.objects.create(keyword="Exploit")
new_Explore = Explore.objects.create(keyword="Explore")
new_Extort = Extort.objects.create(keyword="Extort")
new_Fabricate = Fabricate.objects.create(keyword="Fabricate")
new_Fading = Fading.objects.create(keyword="Fading")
new_Fateful_hour = Fateful_hour.objects.create(keyword="Fateful hour")
new_Fateseal = Fateseal.objects.create(keyword="Fateseal")
new_Fear = Fear.objects.create(keyword="Fear")
new_Ferocious = Ferocious.objects.create(keyword="Ferocious")
new_Fight = Fight.objects.create(keyword="Fight")
new_First_strikeFlanking = First_strike.objects.create(keyword="First strike")
new_Flanking = Flanking.objects.create(keyword="Flanking")
new_Flash = Flash.objects.create(keyword="Flash")
new_Flashback = Flashback.objects.create(keyword="Flashback")
new_Flying = Flying.objects.create(keyword="Flying")
new_Forecast = Forecast.objects.create(keyword="Forecast")
new_Forestcycling = Forestcycling.objects.create(keyword="Forestcycling")
new_Forestwalk = Forestwalk.objects.create(keyword="Forestwalk")
new_Foretell = Foretell.objects.create(keyword="Foretell")
new_Formidable = Formidable.objects.create(keyword="Formidable")
new_Fortify = Fortify.objects.create(keyword="Fortify")
new_Fuse = Fuse.objects.create(keyword="Fuse")
new_Goad = Goad.objects.create(keyword="Goad")
new_Graft = Graft.objects.create(keyword="Graft")
new_Grandeur = Grandeur.objects.create(keyword="Grandeur")
new_Gravestorm = Gravestorm.objects.create(keyword="Gravestorm")
new_Haste = Haste.objects.create(keyword="Haste")
new_Haunt = Haunt.objects.create(keyword="Haunt")
new_Hellbent = Hellbent.objects.create(keyword="Hellbent")
new_Heros_Reward = Heros_Reward.objects.create(keyword="Hero's Reward")
new_Heroic = Heroic.objects.create(keyword="Heroic")
new_Hexproof = Hexproof.objects.create(keyword="Hexproof")
new_Hexproof_from = Hexproof_from.objects.create(keyword="Hexproof from")
new_Hidden_agenda = Hidden_agenda.objects.create(keyword="Hidden agenda")
new_Hideaway = Hideaway.objects.create(keyword="Hideaway")
new_Horsemanship = Horsemanship.objects.create(keyword="Horsemanship")
new_Imprint = Imprint.objects.create(keyword="Imprint")
new_Improvise = Improvise.objects.create(keyword="Improvise")
new_Indestructible = Indestructible.objects.create(keyword="Indestructible")
new_Infect = Infect.objects.create(keyword="Infect")
new_Ingest = Ingest.objects.create(keyword="Ingest")
new_Inspired = Inspired.objects.create(keyword="Inspired")
new_Intimidate = Intimidate.objects.create(keyword="Intimidate")
new_Investigate = Investigate.objects.create(keyword="Investigate")
new_Islandcycling = Islandcycling.objects.create(keyword="Islandcycling")
new_Islandwalk = Islandwalk.objects.create(keyword="Islandwalk")
new_Join_forces = Join_forces.objects.create(keyword="Join forces")
new_Jump_start = Jump_start.objects.create(keyword="Jump-start")
new_Kicker = Kicker.objects.create(keyword="Kicker")
new_Kinfall = Kinfall.objects.create(keyword="Kinfall")
new_Kinship = Kinship.objects.create(keyword="Kinship")
new_Landcycling = Landcycling.objects.create(keyword="Landcycling")
new_Landfall = Landfall.objects.create(keyword="Landfall")
new_Landship = Landship.objects.create(keyword="Landship")
new_Landwalk = Landwalk.objects.create(keyword="Landwalk")
new_Legacy = Legacy.objects.create(keyword="Legacy")
new_Legendary_landwalk = Legendary_landwalk.objects.create(keyword="Legendary landwalk")
new_Level_Up = Level_Up.objects.create(keyword="Level Up")
new_Lieutenant = Lieutenant.objects.create(keyword="Lieutenant")
new_Lifelink = Lifelink.objects.create(keyword="Lifelink")
new_Living_weapon = Living_weapon.objects.create(keyword="Living weapon")
new_Madness = Madness.objects.create(keyword="Madness")
new_Manifest = Manifest.objects.create(keyword="Manifest")
new_Megamorph = Megamorph.objects.create(keyword="Megamorph")
new_Meld = Meld.objects.create(keyword="Meld")
new_Melee = Melee.objects.create(keyword="Melee")
new_Menace = Menace.objects.create(keyword="Menace")
new_Mentor = Mentor.objects.create(keyword="Mentor")
new_Metalcraft = Metalcraft.objects.create(keyword="Metalcraft")
new_Mill = Mill.objects.create(keyword="Mill")
new_Miracle = Miracle.objects.create(keyword="Miracle")
new_Modular = Modular.objects.create(keyword="Modular")
new_Monstrosity = Monstrosity.objects.create(keyword="Monstrosity")
new_Morbid = Morbid.objects.create(keyword="Morbid")
new_Morph = Morph.objects.create(keyword="Morph")
new_Mountaincycling = Mountaincycling.objects.create(keyword="Mountaincycling")
new_Mountainwalk = Mountainwalk.objects.create(keyword="Mountainwalk")
new_Multikicker = Multikicker.objects.create(keyword="Multikicker")
new_Mutate = Mutate.objects.create(keyword="Mutate")
new_Myriad = Myriad.objects.create(keyword="Myriad")
new_Ninjutsu = Ninjutsu.objects.create(keyword="Ninjutsu")
new_Nonbasic_landwalk = Nonbasic_landwalk.objects.create(keyword="Nonbasic landwalk")
new_Outlast = Outlast.objects.create(keyword="Outlast")
new_Overload = Overload.objects.create(keyword="Overload")
new_Parley = Parley.objects.create(keyword="Parley")
new_Partner = Partner.objects.create(keyword="Partner")
new_Partner_with = Partner_with.objects.create(keyword="Partner with")
new_Persist = Persist.objects.create(keyword="Persist")
new_Phasing = Phasing.objects.create(keyword="Phasing")
new_Plainscycling = Plainscycling.objects.create(keyword="Plainscycling")
new_Plainswalk = Plainswalk.objects.create(keyword="Plainswalk")
new_Populate = Populate.objects.create(keyword="Populate")
new_Proliferate = Proliferate.objects.create(keyword="Proliferate")
new_Protection = Protection.objects.create(keyword="Protection")
new_Provoke = Provoke.objects.create(keyword="Provoke")
new_Prowess = Prowess.objects.create(keyword="Prowess")
new_Prowl = Prowl.objects.create(keyword="Prowl")
new_Radiance = Radiance.objects.create(keyword="Radiance")
new_Raid = Raid.objects.create(keyword="Raid")
new_Rally = Rally.objects.create(keyword="Rally")
new_Rampage = Rampage.objects.create(keyword="Rampage")
new_Reach = Reach.objects.create(keyword="Reach")
new_Rebound = Rebound.objects.create(keyword="Rebound")
new_Recover = Recover.objects.create(keyword="Recover")
new_Reinforce = Reinforce.objects.create(keyword="Reinforce")
new_Renown = Renown.objects.create(keyword="Renown")
new_Replicate = Replicate.objects.create(keyword="Replicate")
new_Retrace = Retrace.objects.create(keyword="Retrace")
new_Revolt = Revolt.objects.create(keyword="Revolt")
new_Riot = Riot.objects.create(keyword="Riot")
new_Ripple = Ripple.objects.create(keyword="Ripple")
new_Scavenge = Scavenge.objects.create(keyword="Scavenge")
new_Scry = Scry.objects.create(keyword="Scry")
new_Shadow = Shadow.objects.create(keyword="Shadow")
new_Shroud = Shroud.objects.create(keyword="Shroud")
new_Skulk = Skulk.objects.create(keyword="Skulk")
new_Slivercycling = Slivercycling.objects.create(keyword="Slivercycling")
new_Soulbond = Soulbond.objects.create(keyword="Soulbond")
new_Soulshift = Soulshift.objects.create(keyword="Soulshift")
new_Spectacle = Spectacle.objects.create(keyword="Spectacle")
new_Spell_mastery = Spell_mastery.objects.create(keyword="Spell mastery")
new_Splice = Splice.objects.create(keyword="Splice")
new_Split_second = Split_second.objects.create(keyword="Split second")
new_Storm = Storm.objects.create(keyword="Storm")
new_Strive = Strive.objects.create(keyword="Strive")
new_Sunburst = Sunburst.objects.create(keyword="Sunburst")
new_Support = Support.objects.create(keyword="Support")
new_Surge = Surge.objects.create(keyword="Surge")
new_Surveil = Surveil.objects.create(keyword="Surveil")
new_Suspend = Suspend.objects.create(keyword="Suspend")
new_Swampcycling = Swampcycling.objects.create(keyword="Swampcycling")
new_Swampwalk = Swampwalk.objects.create(keyword="Swampwalk")
new_Sweep = Sweep.objects.create(keyword="Sweep")
new_Tempting_offer = Tempting_offer.objects.create(keyword="Tempting offer")
new_Threshold = Threshold.objects.create(keyword="Threshold")
new_Totem_armor = Totem_armor.objects.create(keyword="Totem armor")
new_Trample = Trample.objects.create(keyword="Trample")
new_Transfigure = Transfigure.objects.create(keyword="Transfigure")
new_Transform = Transform.objects.create(keyword="Transform")
new_Transmute = Transmute.objects.create(keyword="Transmute")
new_Tribute = Tribute.objects.create(keyword="Tribute")
new_Typecycling = Typecycling.objects.create(keyword="Typecycling")
new_Undaunted = Undaunted.objects.create(keyword="Undaunted")
new_Underdog = Underdog.objects.create(keyword="Underdog")
new_Undergrowth = Undergrowth.objects.create(keyword="Undergrowth")
new_Undying = Undying.objects.create(keyword="Undying")
new_Unearth = Unearth.objects.create(keyword="Unearth")
new_Unleash = Unleash.objects.create(keyword="Unleash")
new_Vanishing = Vanishing.objects.create(keyword="Vanishing")
new_Vigilance = Vigilance.objects.create(keyword="Vigilance")
new_Will_of_the_council = Will_of_the_council.objects.create(keyword="Will of the council")
new_Wither = Wither.objects.create(keyword="Wither")
new_Wizardcycling = Wizardcycling.objects.create(keyword="Wizardcycling")


